name: Actualizar archivo JSON

on:
  schedule:
    - cron: '*/2 * * * *'  # Ejecuta cada 30 minutos
  workflow_dispatch:  # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  update-json:
    runs-on: ubuntu-latest  # Aquí no importa tu sistema operativo, esto corre en la nube

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2  # Clona el contenido del repositorio

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Instala la versión de Python

    - name: Install dependencies (optional)
      run: |
        pip install -r requirements.txt  # Instala las dependencias si las tienes en requirements.txt

    - name: Run update script
      run: |
        python update_json.py  # Ejecuta el script Python para actualizar el archivo JSON

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add temperatura.json
        git commit -m "Actualizar archivo JSON automáticamente"
        git push
