name: Actualizar archivo JSON

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos
  workflow_dispatch:  # También permite ejecutar manualmente
jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run update script
      run: |
        python update_json.py

    - name: Set up Git config
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add temperatura.json
        git commit -m "Actualizar archivo JSON automáticamente"
        git push https://${{ secrets.GH_PAT }}@github.com/JeffLcTec/PaginaArqui.git main --force
